# Setup
title: Dylan
tagline: "A Blockchain Developer"
description: "Blockchain Developer"
url: https://duanyytop.github.io
github: https://github.com/duanyytop/duanyytop.github.io
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Dylan
  url: https://github.com/duanyytop
  email: duanyytop@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
